# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.8.6.dev37+g70f9c47.d20250126'
__version_tuple__ = version_tuple = (1, 8, 6, 'dev37', 'g70f9c47.d20250126')
